name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mstksg/get-package@v1
      with:
        apt-get: libsdl2-dev
        brew: sdl2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
